#!/usr/bin/env python3
"""Build the HyperFrames compositions in web/ from timeline.json and web/src/.

Usage: python3 -I scripts/build_web.py
Writes web/assets/timing.js   shot windows, word onsets (film time), grid, landmarks
       web/index.html         the film (52.55 s); only shots with markup are mounted so far
       web-tests/motion-s07-s08/index.html   Stage D motion test: film time 7.40–12.40 s (S06 end → S07 → S08),
                              its own project (assets/ and src/ are symlinks to web/)
Both compositions share web/src/styles.css and web/src/film.js. The film timeline is authored in
film time; the motion test plays a window of it with tweenFromTo, so the two can never drift apart.
"""
import json, os, shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)
tl = json.load(open("timeline.json"))
lines = {l["id"]: l for l in json.load(open("vo/lines.json"))["lines"]}
place = {v["id"]: v["start"] for v in tl["vo"]}
END = tl["length_s"]

# ---------------------------------------------------------------- timing.js
words = {lid: [{"t": round(place[lid] + w["start"], 3), "text": w["text"]} for w in lines[lid]["word_times"]] for lid in place}
shots = {s["id"]: {"start": s["start"], "end": s["end"]} for s in tl["shots"]}
timing = {"P": tl["grid"]["period_s"], "PH": tl["grid"]["phase_s"], "END": END, "shots": shots, "words": words,
          "landmarks": tl["music"]["landmarks"], "sfx": tl["sfx"]}
open("web/assets/timing.js", "w").write("// generated by scripts/build_web.py from timeline.json; do not edit\nwindow.EL = "
                                         + json.dumps(timing, separators=(",", ":")) + ";\n")

# ---------------------------------------------------------------- seeded markup
def mulberry(seed):
    a = seed & 0xFFFFFFFF
    def r():
        nonlocal a
        a = (a + 0x6D2B79F5) & 0xFFFFFFFF
        t = a
        t = ((t ^ (t >> 15)) * (t | 1)) & 0xFFFFFFFF
        t ^= (t + (((t ^ (t >> 7)) * (t | 61)) & 0xFFFFFFFF)) & 0xFFFFFFFF
        return ((t ^ (t >> 14)) & 0xFFFFFFFF) / 4294967296
    return r
rnd = mulberry(20261006)
# "+" markers on a 120 px lattice (MOTION_PHILOSOPHY §2.1: at grid intersections), upper part of the frame
cells = list(dict.fromkeys((1 + int(rnd() * 15), 1 + int(rnd() * 5)) for _ in range(80)))[:28]   # seeded order, no repeats
cross = "".join(f'<div class="cross" style="left:{c * 120 - 7}px;top:{r * 120 - 7}px"></div>' for c, r in cells)

# a plain handset glyph (drawn for this film), so the bubbles read as phone calls, not ticks
HANDSET = ('<svg viewBox="0 0 24 24"><path fill="#fff" d="M7 3h3l1.5 4.5-2 1.5c1 2.2 2.8 4 5 5l1.5-2L21 13.5v3'
           'c0 1.4-1.1 2.5-2.5 2.5C10.5 19 5 13.5 4.5 5.5 4.5 4.1 5.6 3 7 3z"/></svg>')
rb = mulberry(606)
bubbles = []
N_B = 28
for i in range(N_B):
    w = 250 if i < 14 else 300
    spread = 1.0 if i < 20 else 0.55                    # the last wave crowds the centre
    cx, cy = int(960 + (rb() - 0.5) * 1560 * spread), int(540 + (rb() - 0.5) * 760 * spread)
    end_scale = round(0.9 + (i / (N_B - 1)) ** 2 * 2.8, 2)   # later bubbles come at camera: they overflow the frame
    bubbles.append(f'<div class="bubble" data-cx="{cx}" data-cy="{cy}" data-s="{end_scale}" '
                   f'style="left:{cx - w // 2}px;top:{cy - 44}px"><div class="ic">{HANDSET}</div><div class="dots"><i></i><i></i><i></i></div></div>')
bubbles = "".join(bubbles)
seats = "".join('<div class="seat"><div class="av"></div><div class="l1"></div><div class="l2"></div><div class="st"></div>'
                '<div class="tint"></div><div class="ok"></div></div>' for _ in range(32))
MSG = "Dear Parent, Rahul Sharma was marked Present…"      # BRIEF §5 S20, demo data inside the app card
msg = "".join(f'<span class="ch">{c}</span>' for c in MSG)

LOCK = ('<div class="lockup" id="{id}" data-layout-allow-overflow><div class="mark"><div class="glint"></div></div>'
        '<div class="word"><div class="glint"></div></div></div>')
PART = {
 "S01": '<div class="ph" id="s01-book"><span>PLACEHOLDER · H1 3D ledger book render</span></div><div id="s01-ring"></div>'
        '<div class="layer halo-red"><div class="kinetic" id="s01-word"><span class="chrome">REGISTERS</span></div></div>',
 "S06": f'<div class="layer" id="s06-layer">{bubbles}</div>',
 "S07": '<div class="ledger white" id="s07-line"><div class="bloom" data-layout-allow-overflow></div><div class="core"></div></div>',
 "S08": '<div class="ledger white" id="s08-line-w"><div class="bloom" data-layout-allow-overflow></div><div class="core"></div></div>'
        '<div class="ledger brand" id="s08-line-b" style="opacity:0"><div class="bloom" data-layout-allow-overflow></div><div class="core"></div></div>'
        + LOCK.format(id="s08-lock"),
 "S13": '<div class="support halo" id="s13-title"><span class="w chrome" id="s13-w1">Admissions</span><span class="w arrow" id="s13-w2">→</span>'
        '<span class="w chrome" id="s13-w3">Attendance</span></div>'
        f'<div id="s13-plane"><div id="s13-grid">{seats}</div></div>',
 "S20": '<div class="ph" id="s20-phone"><span>PLACEHOLDER · H4 3D phone render</span></div>'
        '<div id="s20-chip">Add-on</div>'
        '<div id="s20-card"><div class="hd"><div class="cardmark"></div><div><div class="who">EduLedger</div>'
        '<div class="sub">School update</div></div><div class="demo">Demo</div></div>'
        f'<div class="msg">{msg}</div><div class="meta"><span id="s20-ticks">✓✓</span></div></div>'
        '<div id="s20-cardnote">Card design: placeholder until EduLedger’s chat card arrives</div>'
        '<div class="support halo" id="s20-text"><div><span class="w chrome" id="s20-w1">Updated</span></div>'
        '<div><span class="w chrome" id="s20-w2">instantly</span></div>'
        '<div><span class="w chrome" id="s20-w3">on</span> <span class="w chrome" id="s20-w4">WhatsApp.</span></div></div>',
 "S26": '<div class="ledger brand" id="s26-line"><div class="bloom" data-layout-allow-overflow></div><div class="core"></div></div>'
        + LOCK.format(id="s26-lock") +
        '<div class="support halo" id="s26-tag"><span class="w chrome" id="s26-w1">Manage</span><span class="w chrome" id="s26-w2">better.</span>'
        '<span class="w chrome" id="s26-w3">Educate</span><span class="w chrome" id="s26-w4">smarter.</span></div>',
}

css = open("web/src/styles.css").read()
GLOBAL_BOTTOM = ('<div id="bg" class="full"></div><div id="glow-red" class="full"></div><div id="glow-brand" class="full"></div>'
                 '<div id="floorwrap" class="full"><div class="floor" id="floor-neutral" data-layout-allow-overflow></div><div class="floor" id="floor-brand" data-layout-allow-overflow></div></div>'
                 f'<div id="crosses" class="full">{cross}</div>')
# overlays are translucent texture by design: tell the layout audit they may sit over text
GLOBAL_TOP = ('<div id="streak" data-layout-allow-occlusion></div><div id="vignette" class="full" data-layout-allow-occlusion></div>'
              '<div id="grain" class="full" data-layout-allow-occlusion></div><div id="flash" class="full" data-layout-allow-occlusion></div>'
              '<div id="corners" class="full" data-layout-allow-occlusion><div class="corner tl"></div><div class="corner tr"></div>'
              '<div class="corner bl"></div><div class="corner br"></div></div>')

def page(name, title, off, dur, only=None, prefix=""):
    secs = []
    for s in tl["shots"]:
        if s["id"] not in PART or (only and s["id"] not in only):
            continue
        a, b = max(s["start"], off), min(s["end"], off + dur)
        if b <= a:
            continue
        secs.append(f'<section id="{s["id"]}" class="clip shot" data-start="{a - off:.4f}" data-duration="{b - a:.4f}" '
                    f'data-track-index="1">{PART[s["id"]]}</section>')
    shots_js = json.dumps([s["id"] for s in tl["shots"] if s["id"] in PART and (not only or s["id"] in only)])
    html = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=1920, height=1080">
<title>{title}</title>
<script src="{prefix}assets/vendor/gsap-3.14.2.min.js"></script>
<script src="{prefix}assets/timing.js"></script>
<script src="{prefix}src/film.js"></script>
<style>
{css}
</style>
</head>
<body>
<div id="root" data-composition-id="main" data-start="0" data-duration="{dur:.4f}" data-width="1920" data-height="1080" data-fps="60">
{GLOBAL_BOTTOM}
{"".join(secs)}
{GLOBAL_TOP}
<audio id="mix" src="assets/audio/mix.wav" data-start="0" data-duration="{dur:.4f}" data-media-start="{off:.4f}" data-track-index="9" data-volume="1"></audio>
</div>
<script>
  window.__timelines = window.__timelines || {{}};
  const film = gsap.timeline({{ paused: true }});
  FILM.build(film, {{ shots: {shots_js} }});
"""
    if off == 0:
        html += "  window.__timelines[\"main\"] = film;\n"
    else:
        html += (f"  const tl = gsap.timeline({{ paused: true }});\n"
                 f"  tl.add(film.tweenFromTo({off:.4f}, {off + dur:.4f}, {{ duration: {dur:.4f}, ease: \"none\" }}), 0);\n"
                 f"  window.__timelines[\"main\"] = tl;\n")
    html += "</script>\n</body>\n</html>\n"
    open(name, "w").write(html)
    print(f"{name}: {len(secs)} shot clips, {dur:.2f} s from film time {off:.2f}")

# assets the pages need
shutil.copy("out/timeline/preview-mix.wav", "web/assets/audio/mix.wav")
page("web/index.html", "EduLedger launch film", 0.0, END)
# the motion test is its own HyperFrames project (one root composition per project), sharing web/'s assets and code
os.makedirs("web-tests/motion-s07-s08", exist_ok=True)
for link in ("assets", "src"):
    p = f"web-tests/motion-s07-s08/{link}"
    if not os.path.islink(p):
        os.symlink(f"../../web/{link}", p)
shutil.copy("web/hyperframes.json", "web-tests/motion-s07-s08/hyperframes.json")
json.dump({"id": "eduledger-motion-s07-s08", "name": "EduLedger motion test S07→S08", "createdAt": "2026-10-06T10:00:00.000Z"},
          open("web-tests/motion-s07-s08/meta.json", "w"), indent=2)
page("web-tests/motion-s07-s08/index.html", "EduLedger motion test S07→S08", 7.40, 5.00, only=["S06", "S07", "S08"])
