#!/usr/bin/env python3
"""Build the HyperFrames compositions in web/ from timeline.json, web/src/ and whatever inputs have landed.

Usage: python3 -I scripts/build_web.py        (or scripts/build_all.sh for build + mix + checks)
Writes web/assets/timing.js        shot windows, word onsets (film time), grid, landmarks, SFX anchors
       web/assets/transcript.json  VO words in film time (for the sync check)
       web/assets/manifest.json    which inputs are REAL and which are PLACEHOLDER, per slot
       web/index.html              the film, 28 shots, 52.55 s
       web-tests/motion-s07-s08/index.html   Stage D motion test (film time 7.40–12.40 s), its own project

Placeholders swap automatically: every slot below resolves to the real file when it exists and to a
labelled placeholder when it does not. Re-run this script (scripts/build_all.sh) after files land.
  ui/<key>.png|jpg|webp         app screenshots (dashboard, students, admissions, attendance, fees, receipt,
                                 payroll, cashbook, parent-chat, phone)
  heroes/H1…H5.png|jpg|webp     hero renders on navy #07111f
  brand/logo-mark.svg, brand/logo-wordmark-on-dark.svg   preferred over the PROVISIONAL PNGs when present
  sfx/Xnn(_v1).wav|mp3          picked up by scripts/mix.py (placeholders in sfx/placeholder/ otherwise)
"""
import glob, json, os, re, shutil, subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)
# draft (default): a missing app screen shows its TEMPORARY MOCK (scripts/build_mocks.mjs, watermarked) if one is built.
# final (EL_MODE=final): mocks are never used; anything missing stays a PLACEHOLDER and scripts/final_gate.py fails.
MODE = os.environ.get("EL_MODE", "draft")
assert MODE in ("draft", "final"), MODE
MOCK_WM = '<div class="mock-wm">MOCK — internal draft</div>'
tl = json.load(open("timeline.json"))
lines = {l["id"]: l for l in json.load(open("vo/lines.json"))["lines"]}
place = {v["id"]: v["start"] for v in tl["vo"]}
END = tl["length_s"]
SH = {s["id"]: s for s in tl["shots"]}

# ---------------------------------------------------------------- timing.js + transcript.json
words = {lid: [{"t": round(place[lid] + w["start"], 3), "end": round(place[lid] + w["end"], 3), "text": w["text"]}
               for w in lines[lid]["word_times"]] for lid in place}
timing = {"P": tl["grid"]["period_s"], "PH": tl["grid"]["phase_s"], "END": END,
          "shots": {s["id"]: {"start": s["start"], "end": s["end"]} for s in tl["shots"]},
          "words": words, "landmarks": tl["music"]["landmarks"], "sfx": tl["sfx"]}
open("web/assets/timing.js", "w").write("// generated by scripts/build_web.py from timeline.json; do not edit\nwindow.EL = "
                                         + json.dumps(timing, separators=(",", ":")) + ";\n")
transcript = [{"text": w["text"], "start": w["t"], "end": w["end"]} for lid in sorted(words) for w in words[lid]]
json.dump(transcript, open("web/assets/transcript.json", "w"), indent=0)

# ---------------------------------------------------------------- input resolvers (REAL or PLACEHOLDER)
manifest = {}
def find(pattern_stem):
    for ext in ("png", "jpg", "jpeg", "webp"):
        hits = sorted(glob.glob(f"{pattern_stem}.{ext}"))
        if hits:
            return hits[0]
    return None
def size(path):
    out = subprocess.run(["ffprobe", "-v", "error", "-show_entries", "stream=width,height", "-of", "csv=p=0", path],
                         capture_output=True, text=True).stdout.strip().split(",")
    return int(out[0]), int(out[1])

UI_LABEL = {"dashboard": "dashboard", "students": "student records", "admissions": "admissions", "attendance": "attendance",
            "fees": "fees / invoices", "receipt": "fee receipt", "payroll": "staff & payroll", "cashbook": "cashbook report",
            "parent-chat": "parent chat card", "phone": "phone view"}
def ui(slot, key, cls="", demo=True, aspect=(16, 9), extra=""):
    """An app screenshot in a frame. `slot` is the element id. Real file: ui/<key>.*; else a labelled placeholder."""
    src = find(f"ui/{key}")
    tag = '<div class="demo-tag">Demo</div>' if demo else ""
    if src:
        os.makedirs("web/assets/ui", exist_ok=True)
        ext = src.rsplit(".", 1)[1]
        dst = f"web/assets/ui/{key}.{ext}"
        shutil.copy(src, dst)
        w, h = size(src)
        manifest.setdefault(f"ui/{key}", {"status": "REAL", "file": src, "size": [w, h], "slots": []})["slots"].append(slot)
        return (f'<div class="uiframe {cls}" id="{slot}" style="aspect-ratio:{w}/{h}"{extra}>'
                f'<div class="uiimg" style="background-image:url(assets/ui/{key}.{ext})"></div><i class="sheen" data-layout-allow-overflow></i>{tag}</div>')
    mock = f"web/assets/ui/mock/{key}.png"
    if MODE == "draft" and os.path.exists(mock):
        w, h = size(mock)
        manifest.setdefault(f"ui/{key}", {"status": "MOCK", "file": mock, "size": [w, h], "slots": []})["slots"].append(slot)
        return (f'<div class="uiframe mock {cls}" id="{slot}" data-mock="ui/{key}" style="aspect-ratio:{w}/{h}"{extra}>'
                f'<div class="uiimg" style="background-image:url(assets/ui/mock/{key}.png)"></div><i class="sheen" data-layout-allow-overflow></i>{tag}</div>')
    manifest.setdefault(f"ui/{key}", {"status": "PLACEHOLDER", "slots": []})["slots"].append(slot)
    return (f'<div class="uiframe ph-ui {cls}" id="{slot}" style="aspect-ratio:{aspect[0]}/{aspect[1]}"{extra}>'
            f'<span>PLACEHOLDER · UI {UI_LABEL[key]} screenshot<em>ui/{key}.png</em></span><i class="sheen" data-layout-allow-overflow></i>{tag}</div>')

HERO_LABEL = {"H1": "3D ledger book", "H2": "3D receipt stack", "H3": "3D rupee coin", "H4": "3D phone", "H5": "3D school building"}
def hero(slot, h, tint="brand"):
    """A hero render. Real file: heroes/<h>.*, used on its own navy with soft edges; code adds rim light only."""
    src = find(f"heroes/{h}")
    if src:
        os.makedirs("web/assets/heroes", exist_ok=True)
        ext = src.rsplit(".", 1)[1]
        shutil.copy(src, f"web/assets/heroes/{h}.{ext}")
        manifest.setdefault(f"heroes/{h}", {"status": "REAL", "file": src, "size": list(size(src)), "slots": []})["slots"].append(slot)
        return (f'<div class="hero {tint}" id="{slot}"><div class="rim"></div>'
                f'<div class="himg" style="background-image:url(assets/heroes/{h}.{ext})"></div></div>')
    manifest.setdefault(f"heroes/{h}", {"status": "PLACEHOLDER", "slots": []})["slots"].append(slot)
    return (f'<div class="hero ph {tint}" id="{slot}"><div class="rim"></div>'
            f'<span>PLACEHOLDER · {h} {HERO_LABEL[h]} render<em>heroes/{h}.png</em></span></div>')

# logo: SVG from the developer wins over the PROVISIONAL PNG cut-outs
for name, svg in (("logo-mark", "brand/logo-mark.svg"), ("logo-wordmark-dark", "brand/logo-wordmark-on-dark.svg")):
    if os.path.exists(svg):
        shutil.copy(svg, f"web/assets/brand/{name}.svg")
        manifest[f"brand/{name}"] = {"status": "REAL", "file": svg}
    else:
        manifest[f"brand/{name}"] = {"status": "PROVISIONAL", "file": f"web/assets/brand/{name}.png"}
LOGO_EXT = {n: ("svg" if manifest[f"brand/{n}"]["status"] == "REAL" else "png") for n in ("logo-mark", "logo-wordmark-dark")}

# ---------------------------------------------------------------- seeded markup
def mulberry(seed):
    a = seed & 0xFFFFFFFF
    def r():
        nonlocal a
        a = (a + 0x6D2B79F5) & 0xFFFFFFFF
        t = a
        t = ((t ^ (t >> 15)) * (t | 1)) & 0xFFFFFFFF
        t ^= (t + (((t ^ (t >> 7)) * (t | 61)) & 0xFFFFFFFF)) & 0xFFFFFFFF
        return ((t ^ (t >> 14)) & 0xFFFFFFFF) / 4294967296
    return r
rnd = mulberry(20261006)
# "+" markers on a 120 px lattice (MOTION_PHILOSOPHY §2.1: at grid intersections), upper part of the frame
cells = list(dict.fromkeys((1 + int(rnd() * 15), 1 + int(rnd() * 5)) for _ in range(80)))[:28]   # seeded order, no repeats
cross = "".join(f'<div class="cross" style="left:{c * 120 - 7}px;top:{r * 120 - 7}px"></div>' for c, r in cells)

# glyphs drawn for this film (no third-party icon sets)
HANDSET = ('<svg viewBox="0 0 24 24"><path fill="#fff" d="M7 3h3l1.5 4.5-2 1.5c1 2.2 2.8 4 5 5l1.5-2L21 13.5v3'
           'c0 1.4-1.1 2.5-2.5 2.5C10.5 19 5 13.5 4.5 5.5 4.5 4.1 5.6 3 7 3z"/></svg>')
SHIELD = ('<svg viewBox="0 0 120 140"><defs><linearGradient id="shg" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#2d60e5"/>'
          '<stop offset="1" stop-color="#8c35e7"/></linearGradient></defs>'
          '<path d="M60 6 L108 24 V66 C108 100 86 124 60 134 C34 124 12 100 12 66 V24 Z" fill="rgba(45,96,229,0.16)" stroke="url(#shg)" stroke-width="6"/>'
          '<rect x="40" y="62" width="40" height="34" rx="6" fill="#f4f6ff"/>'
          '<path d="M47 62 V52 C47 36 73 36 73 52 V62" fill="none" stroke="#f4f6ff" stroke-width="7" stroke-linecap="round"/>'
          '<circle cx="60" cy="78" r="5" fill="#2d60e5"/></svg>')
CHECK = '<svg viewBox="0 0 24 24"><path d="M5 12.5l4.2 4.2L19 7" fill="none" stroke="#fff" stroke-width="3.2" stroke-linecap="round" stroke-linejoin="round"/></svg>'

rb = mulberry(606)
bubbles = []
N_B = 28
for i in range(N_B):
    w = 250 if i < 14 else 300
    spread = 1.0 if i < 20 else 0.55                    # the last wave crowds the centre
    cx, cy = int(960 + (rb() - 0.5) * 1560 * spread), int(540 + (rb() - 0.5) * 760 * spread)
    end_scale = round(0.9 + (i / (N_B - 1)) ** 2 * 2.8, 2)   # later bubbles come at camera: they overflow the frame
    bubbles.append(f'<div class="bubble" data-cx="{cx}" data-cy="{cy}" data-s="{end_scale}" '
                   f'style="left:{cx - w // 2}px;top:{cy - 44}px"><div class="ic">{HANDSET}</div><div class="dots"><i></i><i></i><i></i></div></div>')
bubbles = "".join(bubbles)
rr = mulberry(303)
rings = "".join(f'<div class="ring" style="left:{int(140 + rr() * 1580)}px;top:{int(120 + rr() * 820)}px">'
                f'<div class="halo-ring"></div><div class="ic">{HANDSET}</div></div>' for _ in range(26))
cellsx = "".join(f'<div class="cell{" hd" if r == 0 else ""}"><i style="width:{int(30 + mulberry(r * 31 + c)() * 60)}%"></i></div>'
                 for r in range(9) for c in range(10))
TICKS = []                                            # scribbled ticks on the paper sheet (hand-drawn paths, seeded)
rt = mulberry(77)
for r in range(10):
    for c in range(5):
        x, y = 360 + c * 92 + rt() * 14, 70 + r * 46 + rt() * 6
        TICKS.append(f'<path class="tick" d="M{x:.0f} {y + 12:.0f} l{8 + rt() * 4:.0f} {10 + rt() * 4:.0f} l{16 + rt() * 8:.0f} {-26 - rt() * 8:.0f}"/>')
scribble = "".join(TICKS)
seats = "".join('<div class="seat"><div class="av"></div><div class="l1"></div><div class="l2"></div><div class="st"></div>'
                '<div class="tint"></div><div class="ok"></div></div>' for _ in range(32))
sheets = "".join(f'<div class="sheet" style="left:{560 + i * 14}px;top:{300 - i * 16}px"><i></i><i></i><i></i><i></i><i></i></div>' for i in range(6))
rp = mulberry(909)
particles = "".join(f'<i class="pt" data-dx="{int((rp() - 0.5) * 900)}" data-dy="{int(-200 - rp() * 520)}" '
                    f'style="left:{int(820 + rp() * 280)}px;top:{int(420 + rp() * 220)}px"></i>' for _ in range(48))
MSG = "Dear Parent, Rahul Sharma was marked Present…"      # BRIEF §5 S20, demo data inside the app card
msg = "".join(f'<span class="ch">{c}</span>' for c in MSG)

LOCK = ('<div class="lockup" id="{id}" data-layout-allow-overflow><div class="mark"><div class="glint"></div></div>'
        '<div class="word"><div class="glint"></div></div></div>')
def ledger(id_, kind="brand", extra=""):
    return (f'<div class="ledger {kind}" id="{id_}"{extra}><div class="bloom" data-layout-allow-overflow></div><div class="core"></div></div>')
def kin(id_, text, cls="kinetic", halo="halo"):
    return f'<div class="{halo} layer"><div class="{cls}" id="{id_}"><span class="chrome">{text}</span></div></div>'
def words_html(prefix, ws, cls="support halo", id_=None):
    spans = "".join(f'<span class="w chrome" id="{prefix}-w{i + 1}">{w}</span>' for i, w in enumerate(ws))
    return f'<div class="{cls}" id="{id_ or prefix + "-text"}">{spans}</div>'

# S20: EduLedger's own chat card (BRIEF trademark rule). The real ui/parent-chat.* replaces the code-drawn stand-in.
if find("ui/parent-chat") or MODE == "final":
    S20_CARD = ui("s20-card", "parent-chat", cls="chatreal")
else:
    manifest["ui/parent-chat"] = {"status": "MOCK", "slots": ["s20-card"], "note": "code-drawn card in the site's style (approved at Stage D as a stand-in)"}
    S20_CARD = ('<div id="s20-card" class="mockcard" data-mock="ui/parent-chat"><div class="hd"><div class="cardmark"></div><div><div class="who">EduLedger</div>'
                '<div class="sub">School update</div></div><div class="demo">Demo</div></div>'
                f'<div class="msg">{msg}</div><div class="meta"><span id="s20-ticks">✓✓</span></div>{MOCK_WM}</div>')

# S22: the count-up callout card is code-drawn UI, so it is a MOCK too: drafts only, and only while ui/dashboard is not real.
# With the real dashboard (or in a final build) S22 shows the real screen and a light sweep instead.
S22_CARD = ""
if MODE == "draft" and not find("ui/dashboard"):
    manifest["ui/s22-callout"] = {"status": "MOCK", "slots": ["s22-card"], "note": "count-up callout of the site's demo stats"}
    S22_CARD = ('<div id="s22-card" class="mockcard" data-mock="ui/s22-callout"><div class="cardhd"><div><div class="ov">OVERVIEW</div><div class="school">Greenfield Public School</div></div>'
                '<div class="demo">Demo</div></div><div class="stats">'
                '<div class="stat"><b id="s22-n1">0</b><span>Students</span></div><div class="stat"><b id="s22-n2">0</b><span>Present</span></div>'
                '<div class="stat"><b id="s22-n3">₹0L</b><span>Collected</span></div><div class="stat"><b id="s22-n4">0%</b><span>Attendance</span></div>'
                f'</div>{MOCK_WM}</div>')

PART = {
 "S01": hero("s01-book", "H1", "red") + '<div id="s01-ring"></div>' + kin("s01-word", "REGISTERS", halo="halo-red"),
 "S02": hero("s02-hero", "H2", "red") + kin("s02-word", "RECEIPTS", halo="halo-red"),
 "S03": f'<div class="layer" id="s03-rings">{rings}</div>' + kin("s03-word", "REMINDERS", halo="halo-red"),
 "S04": f'<div id="s04-persp" data-layout-allow-overflow><div id="s04-sheet" data-layout-allow-overflow>{cellsx}</div></div>' + kin("s04-word", "SPREADSHEETS", halo="halo-red"),
 "S05": ('<div id="s05-paper"><div class="rows"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div>'
         f'<svg viewBox="0 0 900 540" id="s05-ticks">{scribble}</svg></div>' + kin("s05-word", "PAPER", halo="halo-red")),
 "S06": f'<div class="layer" id="s06-layer">{bubbles}</div>' + kin("s06-word", "PHONE CALLS", halo="halo-red"),   # the word stays on top of the pile
 "S07": ledger("s07-line", "white"),
 "S08": ledger("s08-line-w", "white") + ledger("s08-line-b", "brand", ' style="opacity:0"') + LOCK.format(id="s08-lock"),
 "S09": (words_html("s09", ["One", "connected", "platform"]) + '<div class="subline halo-soft" id="s09-sub"><span class="chrome dim">for your entire school.</span></div>'
         + ledger("s09-line") + '<div class="persp" id="s09-persp"><div class="tilt">' + ui("s09-ui", "dashboard") + '</div></div>'),
 "S10": kin("s10-word", "Students", cls="kinetic sideword") + '<div class="sidecard">' + ui("s10-ui", "students") + '</div>',
 "S11": kin("s11-word", "Staff", cls="kinetic sideword") + '<div class="sidecard">' + ui("s11-ui", "payroll") + '</div>',
 "S12": kin("s12-word", "Fees", cls="kinetic sideword") + '<div class="sidecard">' + ui("s12-ui", "fees") + '</div>',
 "S13": ('<div class="support halo" id="s13-title"><span class="w chrome" id="s13-w1">Admissions</span><span class="w arrow chrome brandlight" id="s13-w2">→</span>'
         '<span class="w chrome" id="s13-w3">Attendance</span></div>'
         f'<div id="s13-plane"><div id="s13-grid">{seats}</div></div>'),
 "S13b": words_html("s13b", ["One", "clean", "dashboard."]) + '<div class="persp" id="s13b-persp"><div class="tilt">' + ui("s13b-ui", "dashboard") + '</div></div>',
 "S14": words_html("s14", ["Fees?", "Collected."]) + '<div id="s14-spin">' + hero("s14-coin", "H3") + '</div>'
        f'<div id="s14-ok"><div class="okring"></div><div class="okdot">{CHECK}</div></div>',
 "S15": words_html("s15", ["Receipted."]) + ledger("s15-slot") + '<div id="s15-mask" data-layout-allow-overflow>' + ui("s15-ui", "receipt", aspect=(3, 4), extra=" data-layout-allow-overflow") + '</div>',
 "S16": (words_html("s16", ["Tracked,", "in", "real", "time."]) + '<div class="persp" id="s16-persp"><div class="tilt">' + ui("s16-ui", "fees")
         + '</div></div><div id="s16-bar"><div class="track"></div>' + ledger("s16-fill") + '<div id="s16-live"><i></i>Live</div></div>'),
 "S17": (words_html("s17", ["Payroll", "+", "cashbook.", "Done."]) + '<div id="s17-stack">' + ui("s17-ui-a", "payroll") + ui("s17-ui-b", "cashbook")
         + '</div>'),
 "S18": f'<div class="layer" id="s18-sheets">{sheets}</div><div class="layer" id="s18-pts">{particles}</div>' + words_html("s18", ["Less", "paperwork."]),   # particles pass behind the words
 "S19": words_html("s19", ["And", "parents?"]) + '<div id="s19-phone">' + hero("s19-hero", "H4") + '</div>',
 "S20": ('<div id="s20-phonewrap">' + hero("s20-phone", "H4") + '</div>'
         '<div id="s20-chip">Add-on</div>'
         + S20_CARD +
         '<div class="support halo" id="s20-text"><div><span class="w chrome" id="s20-w1">Updated</span></div>'
         '<div><span class="w chrome" id="s20-w2">instantly</span></div>'
         '<div><span class="w chrome" id="s20-w3">on</span> <span class="w chrome" id="s20-w4">WhatsApp.</span></div></div>'),
 "S21": ('<div id="s21-phone">' + hero("s21-hero", "H4") + '</div><div id="s21-chips">'
         + "".join(f'<div class="chip" id="s21-c{i + 1}"><span class="cdot">{CHECK}</span>{t}</div>'
                   for i, t in enumerate(["Attendance", "Fee receipts", "Results"])) + '</div>'),
 "S22": (words_html("s22a", ["Every", "number", "that", "matters."], id_="s22-a")
         + words_html("s22b", ["One", "command", "centre."], id_="s22-b")
         + '<div id="s22-cam"><div class="persp" id="s22-persp" data-layout-allow-occlusion><div class="tilt">' + ui("s22-ui", "dashboard") + '</div></div>'
         + S22_CARD + '</div>'),
 "S23": '<div class="stamp" id="s23-stamp"><div class="stampbox"></div>' + kin("s23-word", "NO SETUP FEE", cls="kinetic stampword glinty") + '</div>',
 "S24": (f'<div id="s24-shield">{SHIELD}</div><div class="stamp" id="s24-stamp"><div class="stampbox"></div>'
         + kin("s24-word", "SECURE BY DESIGN", cls="kinetic stampword glinty") + '</div>'),
 "S25": hero("s25-hero", "H5") + '<div class="stamp" id="s25-stamp">' + kin("s25-word", "BUILT FOR INDIAN SCHOOLS", cls="kinetic stampword small glinty") + '</div>',
 "S26": (ledger("s26-line") + LOCK.format(id="s26-lock")
         + '<div class="support halo" id="s26-tag"><span class="w chrome" id="s26-w1">Manage</span><span class="w chrome" id="s26-w2">better.</span>'
         '<span class="w chrome" id="s26-w3">Educate</span><span class="w chrome" id="s26-w4">smarter.</span></div>'),
 "S27": ('<div id="s27-card"><div class="lockup small" id="s27-lock" data-layout-allow-overflow><div class="mark"><div class="glint"></div></div>'
         '<div class="word"><div class="glint"></div></div></div>'
         '<div class="url halo"><span class="chrome" id="s27-url">eduledger.co.in</span></div>' + ledger("s27-line")
         + '<div id="s27-btn">Get started <span class="arr">→</span></div></div>'),
}
assert set(PART) == set(SH), set(SH) ^ set(PART)

css = open("web/src/styles.css").read()
css = css.replace("logo-mark.png", f"logo-mark.{LOGO_EXT['logo-mark']}").replace("logo-wordmark-dark.png", f"logo-wordmark-dark.{LOGO_EXT['logo-wordmark-dark']}")
GLOBAL_BOTTOM = ('<div id="bg" class="full"></div><div id="glow-red" class="full"></div><div id="glow-brand" class="full"></div>'
                 '<div id="floorwrap" class="full"><div class="floor" id="floor-neutral" data-layout-allow-overflow></div>'
                 '<div class="floor" id="floor-brand" data-layout-allow-overflow></div></div>'
                 f'<div id="crosses" class="full">{cross}</div>')
GLOBAL_TOP = ('<div id="streak"></div><div id="glitch" class="full" data-layout-allow-overflow><i></i><i></i><i></i><i></i></div>'
              '<div id="vignette" class="full"></div><div id="grain" class="full"></div><div id="flash" class="full"></div><div id="fadeout" class="full"></div>'
              '<div id="corners" class="full"><div class="corner tl"></div><div class="corner tr"></div>'
              '<div class="corner bl"></div><div class="corner br"></div></div>')

def _norm(t):
    return re.sub(r"\s+", " ", re.sub(r"[^a-z0-9/.\-]", " ", t.lower())).strip()
def _first_match(phrase, t_min):
    """The kit validator's findAnchorStart(): first transcript word at/after t_min that starts the phrase."""
    toks = phrase.lower().split()
    for i, w in enumerate(transcript):
        if w["start"] < t_min:
            continue
        joined = _norm(" ".join(x["text"] for x in transcript[i:i + len(toks)]))
        if joined.startswith(_norm(phrase)):
            return w["start"]
        if len(toks) == 1 and _norm(phrase).replace(" ", "") in _norm(w["text"]).replace(" ", ""):
            return w["start"]
    return None
def anchor_of(s):
    """data-anchor: the shot's VO word, extended word by word until the kit validator cannot match an earlier
    occurrence (e.g. "EduLedger", "fees", "One" are said more than once)."""
    ws = words[s["line"]]
    i = min(range(len(ws)), key=lambda k: abs(ws[k]["t"] - s["word_onset"]))
    for n in range(1, len(ws) - i + 1):
        phrase = " ".join(w["text"] for w in ws[i:i + n]).strip(".,?!")
        if _first_match(phrase, max(0, s["start"] - 10)) == ws[i]["t"]:
            return phrase
    return phrase

def page(name, title, off, dur, only=None, prefix="", audio="assets/audio/mix.wav"):
    secs = []
    for s in tl["shots"]:
        if only and s["id"] not in only:
            continue
        a, b = max(s["start"], off), min(s["end"], off + dur)
        if b <= a:
            continue
        secs.append(f'<section id="{s["id"]}" class="clip shot" data-start="{a - off:.4f}" data-duration="{b - a:.4f}" '
                    f'data-track-index="{1 + ("S01 S02 S03 S04 S05 S06 S07".find(s["id"]) < 0) + (s["id"] >= "S23")}" '
                    f'data-anchor="{anchor_of(s)}"><div class="inner"><div class="cam">{PART[s["id"]]}</div></div></section>')
    shots_js = json.dumps([s["id"] for s in tl["shots"] if not only or s["id"] in only])
    html = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=1920, height=1080">
<title>{title}</title>
<script src="{prefix}assets/vendor/gsap-3.14.2.min.js"></script>
<script src="{prefix}assets/timing.js"></script>
<script src="{prefix}src/film.js"></script>
<style>
{css}
</style>
</head>
<body>
<div id="root" data-composition-id="main" data-start="0" data-duration="{dur:.4f}" data-width="1920" data-height="1080" data-fps="60">
{GLOBAL_BOTTOM}
{"".join(secs)}
{GLOBAL_TOP}
<audio id="mix" src="{audio}" data-start="0" data-duration="{dur:.4f}" data-media-start="{off:.4f}" data-track-index="9" data-volume="1"></audio>
</div>
<script>
  window.__timelines = window.__timelines || {{}};
  const film = gsap.timeline({{ paused: true }});
  FILM.build(film, {{ shots: {shots_js} }});
"""
    if off == 0:
        html += ("  const tl = film;\n"
                 "  tl.to({}, { duration: EL.END }, 0);   // full length stated inline too (kit preflight reads inline scripts)\n"
                 "  window.__timelines[\"main\"] = tl;\n")
    else:
        html += (f"  const tl = gsap.timeline({{ paused: true }});\n"
                 f"  tl.add(film.tweenFromTo({off:.4f}, {off + dur:.4f}, {{ duration: {dur:.4f}, ease: \"none\" }}), 0);\n"
                 f"  window.__timelines[\"main\"] = tl;\n")
    html += "</script>\n</body>\n</html>\n"
    open(name, "w").write(html)
    print(f"{name}: {len(secs)} shot clips, {dur:.2f} s from film time {off:.2f}")

# the mix: the mastered film mix (scripts/mix.py) when present, else the Stage C preview mix
mix_src = "out/mix/master.wav" if os.path.exists("out/mix/master.wav") else "out/timeline/preview-mix.wav"
os.makedirs("web/assets/audio", exist_ok=True)
shutil.copy(mix_src, "web/assets/audio/mix.wav")
manifest["audio/mix"] = {"status": "MASTER" if "master" in mix_src else "PREVIEW", "file": mix_src}
page("web/index.html", "EduLedger launch film", 0.0, END)
os.makedirs("web-tests/motion-s07-s08", exist_ok=True)
for link in ("assets", "src"):
    p = f"web-tests/motion-s07-s08/{link}"
    if not os.path.islink(p):
        os.symlink(f"../../web/{link}", p)
shutil.copy("web/hyperframes.json", "web-tests/motion-s07-s08/hyperframes.json")
json.dump({"id": "eduledger-motion-s07-s08", "name": "EduLedger motion test S07→S08", "createdAt": "2026-10-06T10:00:00.000Z"},
          open("web-tests/motion-s07-s08/meta.json", "w"), indent=2)
page("web-tests/motion-s07-s08/index.html", "EduLedger motion test S07→S08", 7.40, 5.00, only=["S06", "S07", "S08"])
manifest = {"_mode": MODE, **dict(sorted(manifest.items()))}
json.dump(manifest, open("web/assets/manifest.json", "w"), indent=1)
by = lambda st: sorted(k for k, v in manifest.items() if k != "_mode" and v["status"] in st)
print(f"build mode: {MODE}")
print(f"inputs REAL: {by(('REAL', 'MASTER')) or 'none'}")
print(f"inputs MOCK (internal drafts only): {by(('MOCK',)) or 'none'}")
print(f"inputs PLACEHOLDER/PROVISIONAL/PREVIEW: {by(('PLACEHOLDER', 'PROVISIONAL', 'PREVIEW')) or 'none'}")
