#!/usr/bin/env python3
"""Write VERIFY.md from the reports the gates leave behind (run after scripts/build_all.sh --render).
Usage: python3 -I scripts/write_verify.py
Reads: out/verify/report.json (render), out/mix/report.json, out/sync/report.json, out/audit/check/check-summary.json,
       out/audit/motion.json, out/audit/lint.txt, out/audit/preflight.txt, web/assets/manifest.json, timeline.json
"""
import datetime, json, os, re, subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)
J = lambda p: json.load(open(p))
tl, rv, mx, sy = J("timeline.json"), J("out/verify/report.json"), J("out/mix/report.json"), J("out/sync/report.json")
ck, mo, man = J("out/audit/check/check-summary.json"), J("out/audit/motion.json"), J("web/assets/manifest.json")
lint = open("out/audit/lint.txt").read() if os.path.exists("out/audit/lint.txt") else ""
pre = open("out/audit/preflight.txt").read() if os.path.exists("out/audit/preflight.txt") else ""
ok = lambda b: "✅" if b else "❌"
f = rv["format"]; c = rv["cuts"]; a = rv["audio"]
lint_sum = (re.findall(r"(\d+) error\(s\), (\d+) warning\(s\)", lint) or [("?", "?")])[-1]
pre_ok = "all preflight checks passed" in pre
items = {k: v for k, v in man.items() if not k.startswith("_")}
real = sorted(k for k, v in items.items() if v["status"] in ("REAL", "MASTER"))
mocks = sorted(k for k, v in items.items() if v["status"] == "MOCK")
ph = sorted(k for k, v in items.items() if v["status"] not in ("REAL", "MASTER", "MOCK"))
sfx_real = sorted(k for k, v in mx["sfx"].items() if v["status"] == "REAL")
leads = [r["lead_s"] for r in sy["exact"]["rows"]]

L = []
w = L.append
w("# EduLedger launch film: VERIFY (Stage E draft" + (" — INTERNAL: contains temporary mocks" if mocks else "") + ")\n")
w(f"Generated by `scripts/write_verify.py` on {datetime.date.today()} from the gate reports. Video: `{rv['video']}` ({rv['size_mb']} MB).\n")
w("## Summary\n")
w("| Gate | Result | |")
w("|---|---|---|")
w(f"| Format | {f['width']}×{f['height']}, {f['fps']} fps, {f['frames']} frames (plan {f['expected_frames']}), {f['duration_s']:.3f} s, {f['vcodec']} {f['pix_fmt']}, {f['acodec']} {f['audio_rate']} Hz ×{f['audio_channels']} | {ok(f['frames'] == f['expected_frames'] and f['width'] == 1920)} |")
w(f"| Cuts in the render vs `timeline.json` | **{c['ok']}/{c['planned']}**: {c['on_plan']} peak on the planned frame ±1; {c['exit_led']} exit-led (the outgoing exit peaks 2–4 frames early and the picture still changes sharply on the planned frame; confirmed in the strips). Other sharp changes are in-shot hits, not cuts: " + ", ".join(f"{x[2]} {x[1]:.2f} s" for x in c['unplanned_spikes']) + f" | {ok(c['ok'] == c['planned'])} |")
w(f"| Sync (kit `validate-beat-sync.mjs`) | {sy['kit_validator']['ok']}/{sy['kit_validator']['ok'] + sy['kit_validator']['fail']} OK (−0.2 ≤ word − cut ≤ 1.8 s) | {ok(sy['kit_validator']['fail'] == 0)} |")
w(f"| Sync (exact word + grid) | {sy['exact']['ok']}/{len(sy['exact']['rows'])} OK; cut leads its word by {min(leads) * 1000:.0f}–{max(leads) * 1000:.0f} ms; max {max(r['off_grid_ms'] for r in sy['exact']['rows'])} ms off the beat grid | {ok(sy['exact']['fail'] == 0)} |")
w(f"| Loudness (delivered file) | {a['integrated_lufs']} LUFS, true peak {a['true_peak_dbtp']} dBTP, LRA {a['lra_lu']} LU (target −14 LUFS, < −1 dBTP) | {ok(a['pass'])} |")
w(f"| Mix | VO 1.0 (normalised to −16 LUFS, {mx['vo_gain_db']:+.1f} dB); SFX gains 0.2–0.4; music {mx['music_trim_db']} dB, ducked {mx['music_duck_under_vo_db']} dB under the VO (VO {mx['vo_over_music_db']} dB over the music); master {mx['mastering']}: WAV {mx['integrated_lufs']} LUFS / {mx['true_peak_dbtp']} dBTP | {ok(mx['pass'])} |")
w(f"| `hyperframes lint` | {lint_sum[0]} errors, {lint_sum[1]} warnings (track density: readability advice for one-file films) | {ok(lint_sum[0] == '0')} |")
w(f"| `hyperframes check`, 2 points per shot | {'passed' if ck['ok'] else 'FAILED'}; layout at {ck['layout_times']} times; **contrast {ck['contrast']['passed']}/{ck['contrast']['checked']}** text checks at {len(ck['contrast_times'])} times; {len(ck['findings'])} info notes (intentional overflow during transitions) | {ok(ck['ok'] and ck['contrast']['passed'] == ck['contrast']['checked'] and ck['contrast']['checked'] > 0)} |")
w(f"| Kit preflight | {'all checks passed' if pre_ok else 'see out/audit/preflight.txt'} | {ok(pre_ok)} |")
st = rv["stillness"]
gate = subprocess.run(["python3", "-I", "scripts/final_gate.py"], capture_output=True, text=True)
gate_line = next((l for l in gate.stdout.splitlines() if l.startswith("FINAL GATE")), "FINAL GATE: ?")
w(f"| **Final gate** (`scripts/final_gate.py`) | {gate_line.replace('FINAL GATE: ', '').replace('; a final render is not allowed:', '')}" + (" — expected for an internal draft: this film may not be released as final" if gate.returncode else "") + f" | {'⛔' if gate.returncode else '✅'} |")
w(f"| Stillness (P6 ≤ 20 %, Stage A rule) | {st['near_still_pct']} % near-still frame to frame ({st['near_still_pct_at_1_30s']} % at 1/30 s); runs ≥ 0.5 s: " + ("; ".join(f"{a_}–{b_} s ({sh})" for a_, b_, sh in st['runs_over_0_5s']) or "none") + f" | {ok(st['near_still_pct'] <= 20)} |")
w("")
w("## MOTION_PHILOSOPHY §4 checklist and §5 anti-patterns\n")
w("Measured in the browser by `scripts/motion_audit.mjs`; the frame items come from the render.\n")
w("| Item | Result | |")
w("|---|---|---|")
for it in mo["items"]:
    w(f"| {it['item']} | {it['detail']} | {ok(it['ok'])} |")
w(f"| Palette ≤ 5 meanings | navy canvas · brand light #2D60E5→#8C35E7 · chaos red (S01–S06 only) · present/paid green (from S13) · white type. Paper in S05/S18 is an object's own cream, and the logo keeps its own colours. | ✅ |")
w(f"| One callback minimum | the ledger line: S07, S08, every whip streak, S09, S15, S16, S26, S27; the logo crystallises in S08 and again in S26 | ✅ |")
w(f"| Visual verification | 2 fps contact sheets and a 7-frame strip per cut, all viewed (`out/verify/`) | ✅ |")
w("")
w("## Cuts, frame by frame\n")
w("| Shot | Transition in | Planned (s) | Planned frame | Biggest change at | Offset | Change on the planned frame (local median) | |")
w("|---|---|---|---|---|---|---|---|")
for r in c["rows"]:
    w(f"| {r['shot']} | {r['transition']} | {r['planned_s']:.3f} | {r['planned_frame']} | {r['peak_frame']} | {r['offset_frames']:+d} | {r['change_at_planned_frame']} ({r['local_median']}) | {r['kind']} {ok(r['ok'])} |")
w("")
w("## Inputs in this render\n")
w(f"- **Real:** {', '.join(real) or 'none'}.")
w(f"- **MOCK (temporary, internal drafts only, watermarked \"MOCK — internal draft\"):** {', '.join(mocks) or 'none'}.")
w(f"- **Placeholder / provisional:** {', '.join(ph)}.")
w(f"- Build mode: **{man.get('_mode', 'draft')}**. A final build never uses mocks, and `scripts/final_gate.py` fails the final render while any MOCK or PLACEHOLDER remains.")
w(f"- **SFX:** real {', '.join(sfx_real) or 'none'}; the other {len(mx['sfx']) - len(sfx_real)} are the synth placeholders in `sfx/placeholder/`.")
w("- Every placeholder swaps in automatically when its file lands: `scripts/build_all.sh --render` rebuilds, remixes, re-checks, re-renders and rewrites this file.")
w("")
w("## Files\n")
w(f"- Contact sheets (2 fps): {', '.join('`' + s + '`' for s in rv['sheets'])}")
w(f"- Cut strips (frames −6, −3, −1, 0, +1, +3, +6): {', '.join('`' + s + '`' for s in rv['strips'])}")
w("- Reports: `out/verify/report.json`, `out/mix/report.json`, `out/sync/report.json`, `out/audit/check/`, `out/audit/motion.json`")
open("VERIFY.md", "w").write("\n".join(L) + "\n")
print("VERIFY.md written")
