#!/usr/bin/env python3
"""Generate src/cues.js from the shared timing spine (src/cues.json) and the soundtrack peaks (src/waveform.json).

Usage: python3 -I scripts/build_cues.py
The picture reads window.CUES / window.WAVE; the soundtrack synthesizer reads the same cues.json, so a timing change
in one place moves picture and sound together. Re-run after compose_audio.py (the waveform panel shows the real mix).
"""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
cues = json.load(open(os.path.join(ROOT, "src/cues.json")))
wave = json.load(open(os.path.join(ROOT, "src/waveform.json")))
with open(os.path.join(ROOT, "src/cues.js"), "w") as f:
    f.write("// GENERATED by scripts/build_cues.py from src/cues.json + src/waveform.json. Do not edit by hand.\n")
    f.write("window.CUES = " + json.dumps(cues, separators=(",", ":")) + ";\n")
    f.write("window.WAVE = " + json.dumps(wave, separators=(",", ":")) + ";\n")
print("src/cues.js:", len(cues["chapters"]), "chapters,", wave["bins"], "waveform bins")
